package repo

import (
	_ "embed"
	"strings"
)

//go:embed runtime/gen_repo.go
var genericRuntimeSource string

func genericRuntimeTemplate(packageName string) string {
	const packageDeclaration = "package runtime\n"
	const generatedHeader = "// Code generated by mfd-generator; DO NOT EDIT.\n\n//nolint:all\n"

	return generatedHeader +
		strings.Replace(genericRuntimeSource, packageDeclaration, "package "+packageName+"\n", 1) +
		"\n" + repoRuntimeGlueTemplate
}

const repoRuntimeGlueTemplate = `
// ApplyFilter adapts a generated Filter to a query applier.
func ApplyFilter(filter Filter) Applier {
	return func(query *orm.Query) (*orm.Query, error) {
		return filter.Apply(query), nil
	}
}

// ApplyPager adapts a generated Pager to a query applier.
func ApplyPager(pager Pager) Applier {
	return func(query *orm.Query) (*orm.Query, error) {
		return pager.Apply(query), nil
	}
}

// ApplyOp adapts a legacy query operation to a query applier.
func ApplyOp(operation OpFunc) Applier {
	return func(query *orm.Query) (*orm.Query, error) {
		operation(query)
		return query, nil
	}
}
`
